#!/usr/bin/perl
# --
# scripts/apache2-perl-startup.pl - to load the modules if mod_perl is used
# Copyright (C) 2001-2015 OTRS AG, http://otrs.com/
# --
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU AFFERO General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
# or see http://www.gnu.org/licenses/agpl.txt.
# --

use strict;
use warnings;

# Make sure we are in a sane environment.
$ENV{MOD_PERL} =~ /mod_perl/ || die "MOD_PERL not used!";

BEGIN {

    # switch to unload_package_xs, the PP version is broken in Perl 5.10.1.
    # see http://rt.perl.org/rt3//Public/Bug/Display.html?id=72866
    $ModPerl::Util::DEFAULT_UNLOAD_METHOD = 'unload_package_xs';    ## no critic

    # set $0 to index.pl if it is not an existing file:
    # on Fedora, $0 is not a path which would break OTRS.
    # see bug # 8533
    if ( !-e $0 ) {
        $0 = '/opt/otrs/bin/cgi-bin/index.pl';
    }
}

use Apache2::RequestRec;
use ModPerl::Util;

use lib "/opt/otrs/";
use lib "/opt/otrs/Kernel/cpan-lib";
use lib "/opt/otrs/Custom";

# Preload frequently used modules to speed up client spawning.
use CGI ();
CGI->compile(':cgi');
use CGI::Carp ();

use Apache::DBI;

# enable this if you use mysql
#use DBD::mysql ();
#use Kernel::System::DB::mysql;

# enable this if you use postgresql
#use DBD::Pg ();
#use Kernel::System::DB::postgresql;

# enable this if you use oracle
#use DBD::Oracle ();
#use Kernel::System::DB::oracle;

# core modules
use Kernel::Config;
use Kernel::System::ACL::DB::ACL;
use Kernel::System::Auth;
use Kernel::System::Auth::DB;
use Kernel::System::Auth::HTTPBasicAuth;
use Kernel::System::AuthSession;
use Kernel::System::AuthSession::DB;
use Kernel::System::AuthSession::FS;
use Kernel::System::AutoResponse;
use Kernel::System::CSV;
use Kernel::System::Cache;
use Kernel::System::Cache::FileStorable;
use Kernel::System::CheckItem;
use Kernel::System::CloudService;
use Kernel::System::Crypt;
use Kernel::System::Crypt::PGP;
use Kernel::System::Crypt::SMIME;
use Kernel::System::CustomerAuth;
use Kernel::System::CustomerAuth::DB;
use Kernel::System::CustomerAuth::HTTPBasicAuth;
use Kernel::System::CustomerCompany;
use Kernel::System::CustomerCompany::DB;
use Kernel::System::CustomerCompany::Event::CustomerUserUpdate;
use Kernel::System::CustomerCompany::Event::TicketUpdate;
use Kernel::System::CustomerGroup;
use Kernel::System::CustomerUser;
use Kernel::System::CustomerUser::DB;
use Kernel::System::CustomerUser::Event::ServiceMemberUpdate;
use Kernel::System::CustomerUser::Event::TicketUpdate;
use Kernel::System::CustomerUser::Preferences::DB;
use Kernel::System::DynamicField;
use Kernel::System::DynamicField::Backend;
use Kernel::System::DynamicField::Driver::Base;
use Kernel::System::DynamicField::Driver::BaseDateTime;
use Kernel::System::DynamicField::Driver::BaseSelect;
use Kernel::System::DynamicField::Driver::BaseText;
use Kernel::System::DynamicField::Driver::Checkbox;
use Kernel::System::DynamicField::Driver::Date;
use Kernel::System::DynamicField::Driver::DateTime;
use Kernel::System::DynamicField::Driver::Dropdown;
use Kernel::System::DynamicField::Driver::Multiselect;
use Kernel::System::DynamicField::Driver::ProcessManagement::ActivityID;
use Kernel::System::DynamicField::Driver::ProcessManagement::ProcessID;
use Kernel::System::DynamicField::Driver::Text;
use Kernel::System::DynamicField::Driver::TextArea;
use Kernel::System::DynamicField::ObjectType::Article;
use Kernel::System::DynamicField::ObjectType::Ticket;
use Kernel::System::DynamicFieldValue;
use Kernel::System::Email;
use Kernel::System::Email::DoNotSendEmail;
use Kernel::System::Email::Sendmail;
use Kernel::System::EmailParser;
use Kernel::System::Encode;
use Kernel::System::Environment;
use Kernel::System::Event;
use Kernel::System::EventHandler;
use Kernel::System::FileTemp;
use Kernel::System::GenericAgent;
use Kernel::System::GenericAgent::AutoPriorityIncrease;
use Kernel::System::GenericAgent::NotifyAgentGroupOfCustomQueue;
use Kernel::System::GenericAgent::NotifyAgentGroupWithWritePermission;
use Kernel::System::GenericAgent::TriggerEscalationStartEvents;
use Kernel::System::GenericInterface::DebugLog;
use Kernel::System::GenericInterface::ObjectLockState;
use Kernel::System::GenericInterface::Webservice;
use Kernel::System::GenericInterface::WebserviceHistory;
use Kernel::System::Group;
use Kernel::System::HTMLUtils;
use Kernel::System::JSON;
use Kernel::System::LinkObject;
use Kernel::System::LinkObject::Ticket;
use Kernel::System::Loader;
use Kernel::System::Lock;
use Kernel::System::Log;
use Kernel::System::Log::File;
use Kernel::System::Log::SysLog;
use Kernel::System::MailAccount;
use Kernel::System::Main;
use Kernel::System::Notification;
use Kernel::System::NotificationEvent;
use Kernel::System::OTRSBusiness;
use Kernel::System::ObjectManager;
use Kernel::System::PDF;
use Kernel::System::PID;
use Kernel::System::Package;
use Kernel::System::Package::Event::SupportDataSend;
use Kernel::System::PostMaster;
use Kernel::System::PostMaster::DestQueue;
use Kernel::System::PostMaster::Filter;
use Kernel::System::PostMaster::Filter::CMD;
use Kernel::System::PostMaster::Filter::ExternalTicketNumberRecognition;
use Kernel::System::PostMaster::Filter::FollowUpArticleTypeCheck;
use Kernel::System::PostMaster::Filter::Match;
use Kernel::System::PostMaster::Filter::MatchDBSource;
use Kernel::System::PostMaster::Filter::NewTicketReject;
use Kernel::System::PostMaster::FollowUp;
use Kernel::System::PostMaster::LoopProtection;
use Kernel::System::PostMaster::LoopProtection::DB;
use Kernel::System::PostMaster::LoopProtection::FS;
use Kernel::System::PostMaster::NewTicket;
use Kernel::System::PostMaster::Reject;
use Kernel::System::Priority;
use Kernel::System::ProcessManagement::Activity;
use Kernel::System::ProcessManagement::ActivityDialog;
use Kernel::System::ProcessManagement::DB::Activity;
use Kernel::System::ProcessManagement::DB::ActivityDialog;
use Kernel::System::ProcessManagement::DB::Entity;
use Kernel::System::ProcessManagement::DB::Process;
use Kernel::System::ProcessManagement::DB::Process::State;
use Kernel::System::ProcessManagement::DB::Transition;
use Kernel::System::ProcessManagement::DB::TransitionAction;
use Kernel::System::ProcessManagement::Process;
use Kernel::System::ProcessManagement::Transition;
use Kernel::System::ProcessManagement::TransitionAction;
use Kernel::System::ProcessManagement::TransitionAction::Base;
use Kernel::System::ProcessManagement::TransitionAction::DynamicFieldSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketArticleCreate;
use Kernel::System::ProcessManagement::TransitionAction::TicketCreate;
use Kernel::System::ProcessManagement::TransitionAction::TicketCustomerSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketLockSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketOwnerSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketQueueSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketResponsibleSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketSLASet;
use Kernel::System::ProcessManagement::TransitionAction::TicketServiceSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketStateSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketTitleSet;
use Kernel::System::ProcessManagement::TransitionAction::TicketTypeSet;
use Kernel::System::ProcessManagement::TransitionValidation::ValidateDemo;
use Kernel::System::Queue;
use Kernel::System::Queue::Event::TicketAcceleratorUpdate;
use Kernel::System::Queue::PreferencesDB;
use Kernel::System::ReferenceData;
use Kernel::System::Registration;
use Kernel::System::SLA;
use Kernel::System::SLA::PreferencesDB;
use Kernel::System::Salutation;
use Kernel::System::Scheduler;
use Kernel::System::Scheduler::TaskHandler;
use Kernel::System::Scheduler::TaskHandler::GenericInterface;
use Kernel::System::Scheduler::TaskHandler::RegistrationUpdate;
use Kernel::System::Scheduler::TaskHandler::Test;
use Kernel::System::Scheduler::TaskManager;
use Kernel::System::SearchProfile;
use Kernel::System::Service;
use Kernel::System::Service::PreferencesDB;
use Kernel::System::Signature;
use Kernel::System::Spelling;
use Kernel::System::StandardTemplate;
use Kernel::System::State;
use Kernel::System::Stats;
use Kernel::System::Stats::Dynamic::Ticket;
use Kernel::System::Stats::Dynamic::TicketAccountedTime;
use Kernel::System::Stats::Dynamic::TicketList;
use Kernel::System::Stats::Dynamic::TicketSolutionResponseTime;
use Kernel::System::Stats::Static::StateAction;
use Kernel::System::StdAttachment;
use Kernel::System::SupportBundleGenerator;
use Kernel::System::SupportDataCollector;
use Kernel::System::SupportDataCollector::Plugin::Database::TablePresence;
use Kernel::System::SupportDataCollector::Plugin::Database::mssql::Size;
use Kernel::System::SupportDataCollector::Plugin::Database::mssql::Version;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::Charset;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::MaxAllowedPacket;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::Performance;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::Size;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::StorageEngine;
use Kernel::System::SupportDataCollector::Plugin::Database::mysql::Version;
use Kernel::System::SupportDataCollector::Plugin::Database::oracle::NLS;
use Kernel::System::SupportDataCollector::Plugin::Database::oracle::Version;
use Kernel::System::SupportDataCollector::Plugin::Database::postgresql::Charset;
use Kernel::System::SupportDataCollector::Plugin::Database::postgresql::DateStyle;
use Kernel::System::SupportDataCollector::Plugin::Database::postgresql::Size;
use Kernel::System::SupportDataCollector::Plugin::Database::postgresql::Version;
use Kernel::System::SupportDataCollector::Plugin::OS::DiskPartitionOTRS;
use Kernel::System::SupportDataCollector::Plugin::OS::DiskSpace;
use Kernel::System::SupportDataCollector::Plugin::OS::DiskSpacePartitions;
use Kernel::System::SupportDataCollector::Plugin::OS::Distribution;
use Kernel::System::SupportDataCollector::Plugin::OS::KernelVersion;
use Kernel::System::SupportDataCollector::Plugin::OS::Load;
use Kernel::System::SupportDataCollector::Plugin::OS::PerlModules;
use Kernel::System::SupportDataCollector::Plugin::OS::PerlVersion;
use Kernel::System::SupportDataCollector::Plugin::OS::Swap;
use Kernel::System::SupportDataCollector::Plugin::OTRS::ConfigSettings;
use Kernel::System::SupportDataCollector::Plugin::OTRS::DatabaseRecords;
use Kernel::System::SupportDataCollector::Plugin::OTRS::DefaultSOAPUser;
use Kernel::System::SupportDataCollector::Plugin::OTRS::DefaultUser;
use Kernel::System::SupportDataCollector::Plugin::OTRS::ErrorLog;
use Kernel::System::SupportDataCollector::Plugin::OTRS::FQDN;
use Kernel::System::SupportDataCollector::Plugin::OTRS::FileSystemWritable;
use Kernel::System::SupportDataCollector::Plugin::OTRS::PackageDeployment;
use Kernel::System::SupportDataCollector::Plugin::OTRS::PackageList;
use Kernel::System::SupportDataCollector::Plugin::OTRS::SchedulerRunning;
use Kernel::System::SupportDataCollector::Plugin::OTRS::SystemID;
use Kernel::System::SupportDataCollector::Plugin::OTRS::Ticket::IndexModule;
use Kernel::System::SupportDataCollector::Plugin::OTRS::Ticket::OpenTickets;
use Kernel::System::SupportDataCollector::Plugin::OTRS::Ticket::SearchIndexModule;
use Kernel::System::SupportDataCollector::Plugin::OTRS::Ticket::StaticDBOrphanedRecords;
use Kernel::System::SupportDataCollector::Plugin::OTRS::Version;
use Kernel::System::SupportDataCollector::Plugin::Webserver::Apache::LoadedModules;
use Kernel::System::SupportDataCollector::Plugin::Webserver::Apache::Performance;
use Kernel::System::SupportDataCollector::Plugin::Webserver::EnvironmentVariables;
use Kernel::System::SupportDataCollector::Plugin::Webserver::IIS::Performance;
use Kernel::System::SupportDataCollector::Plugin::Webserver::Version;
use Kernel::System::SupportDataCollector::PluginBase;
use Kernel::System::SysConfig;
use Kernel::System::SysConfig::PriorityValidate;
use Kernel::System::SysConfig::QueueValidate;
use Kernel::System::SysConfig::StateValidate;
use Kernel::System::SystemAddress;
use Kernel::System::SystemData;
use Kernel::System::SystemMaintenance;
use Kernel::System::TemplateGenerator;
use Kernel::System::Ticket;
use Kernel::System::Ticket::Acl::CloseParentAfterClosedChilds;
use Kernel::System::Ticket::Article;
use Kernel::System::Ticket::ArticleSearchIndex::RuntimeDB;
use Kernel::System::Ticket::ArticleSearchIndex::StaticDB;
use Kernel::System::Ticket::ArticleStorageDB;
use Kernel::System::Ticket::ArticleStorageFS;
use Kernel::System::Ticket::ColumnFilter;
use Kernel::System::Ticket::CustomerPermission::CustomerIDCheck;
use Kernel::System::Ticket::CustomerPermission::CustomerUserIDCheck;
use Kernel::System::Ticket::CustomerPermission::GroupCheck;
use Kernel::System::Ticket::Event::ArchiveRestore;
use Kernel::System::Ticket::Event::ArticleSearchIndex;
use Kernel::System::Ticket::Event::DynamicFieldFromCustomerUser;
use Kernel::System::Ticket::Event::ForceOwnerReset;
use Kernel::System::Ticket::Event::ForceState;
use Kernel::System::Ticket::Event::ForceUnlock;
use Kernel::System::Ticket::Event::GenericAgent;
use Kernel::System::Ticket::Event::NotificationEvent;
use Kernel::System::Ticket::Event::ResponsibleAutoSet;
use Kernel::System::Ticket::Event::Test;
use Kernel::System::Ticket::Event::TicketAcceleratorUpdate;
use Kernel::System::Ticket::Event::TicketDynamicFieldDefault;
use Kernel::System::Ticket::Event::TicketEscalationIndex;
use Kernel::System::Ticket::Event::TicketNewMessageUpdate;
use Kernel::System::Ticket::Event::TicketPendingTimeReset;
use Kernel::System::Ticket::Event::TicketProcessTransitions;
use Kernel::System::Ticket::Event::TriggerEscalationStopEvents;
use Kernel::System::Ticket::IndexAccelerator::RuntimeDB;
use Kernel::System::Ticket::IndexAccelerator::StaticDB;
use Kernel::System::Ticket::Number::AutoIncrement;
use Kernel::System::Ticket::Number::Date;
use Kernel::System::Ticket::Number::DateChecksum;
use Kernel::System::Ticket::Number::Random;
use Kernel::System::Ticket::Permission::GroupCheck;
use Kernel::System::Ticket::Permission::OwnerCheck;
use Kernel::System::Ticket::Permission::ResponsibleCheck;
use Kernel::System::Ticket::Permission::WatcherCheck;
use Kernel::System::Ticket::TicketACL;
use Kernel::System::Ticket::TicketSearch;
use Kernel::System::Time;
use Kernel::System::Type;
use Kernel::System::User;
use Kernel::System::User::Preferences::DB;
use Kernel::System::Valid;
use Kernel::System::VariableCheck;
use Kernel::System::VirtualFS;
use Kernel::System::VirtualFS::DB;
use Kernel::System::VirtualFS::FS;
use Kernel::System::Web::InterfaceAgent;
use Kernel::System::Web::InterfaceCustomer;
use Kernel::System::Web::InterfaceInstaller;
use Kernel::System::Web::InterfacePublic;
use Kernel::System::Web::Request;
use Kernel::System::Web::UploadCache;
use Kernel::System::Web::UploadCache::DB;
use Kernel::System::Web::UploadCache::FS;
use Kernel::System::WebUserAgent;
use Kernel::System::XML;
use Kernel::System::YAML;

# generic interface modules
use Kernel::GenericInterface::Debugger;
use Kernel::GenericInterface::Event::Handler;
use Kernel::GenericInterface::Invoker;
use Kernel::GenericInterface::Invoker::Test::Test;
use Kernel::GenericInterface::Invoker::Test::TestSimple;
use Kernel::GenericInterface::Mapping;
use Kernel::GenericInterface::Mapping::Simple;
use Kernel::GenericInterface::Mapping::Test;
use Kernel::GenericInterface::Operation;
use Kernel::GenericInterface::Operation::Common;
use Kernel::GenericInterface::Operation::Session::Common;
use Kernel::GenericInterface::Operation::Session::SessionCreate;
use Kernel::GenericInterface::Operation::Test::Test;
use Kernel::GenericInterface::Operation::Ticket::Common;
use Kernel::GenericInterface::Operation::Ticket::TicketCreate;
use Kernel::GenericInterface::Operation::Ticket::TicketGet;
use Kernel::GenericInterface::Operation::Ticket::TicketSearch;
use Kernel::GenericInterface::Operation::Ticket::TicketUpdate;
use Kernel::GenericInterface::Provider;
use Kernel::GenericInterface::Requester;
use Kernel::GenericInterface::Transport;
use Kernel::GenericInterface::Transport::HTTP::REST;
use Kernel::GenericInterface::Transport::HTTP::SOAP;
use Kernel::GenericInterface::Transport::HTTP::Test;

# language modules
use Kernel::Language::ar_SA;
use Kernel::Language::bg;
use Kernel::Language::ca;
use Kernel::Language::cs;
use Kernel::Language::da;
use Kernel::Language::de;
use Kernel::Language::el;
use Kernel::Language::en;
use Kernel::Language::en_CA;
use Kernel::Language::en_GB;
use Kernel::Language::en_CA;
use Kernel::Language::en_GB;
use Kernel::Language::es;
use Kernel::Language::es_CO;
use Kernel::Language::es_MX;
use Kernel::Language::es_CO;
use Kernel::Language::es_MX;
use Kernel::Language::et;
use Kernel::Language::fa;
use Kernel::Language::fi;
use Kernel::Language::fr;
use Kernel::Language::fr_CA;
use Kernel::Language::fr_CA;
use Kernel::Language::he;
use Kernel::Language::hi;
use Kernel::Language::hr;
use Kernel::Language::hu;
use Kernel::Language::it;
use Kernel::Language::ja;
use Kernel::Language::lt;
use Kernel::Language::lv;
use Kernel::Language::ms;
use Kernel::Language::nb_NO;
use Kernel::Language::nl;
use Kernel::Language::pl;
use Kernel::Language::pt;
use Kernel::Language::pt_BR;
use Kernel::Language::pt_BR;
use Kernel::Language::ru;
use Kernel::Language::sk_SK;
use Kernel::Language::sl;
use Kernel::Language::sr_Cyrl;
use Kernel::Language::sr_Latn;
use Kernel::Language::sv;
use Kernel::Language::sw;
use Kernel::Language::tr;
use Kernel::Language::uk;
use Kernel::Language::vi_VN;
use Kernel::Language::zh_CN;
use Kernel::Language::zh_TW;

# web agent middle ware modules
use Kernel::Modules::AgentBook;
use Kernel::Modules::AgentCustomerInformationCenter;
use Kernel::Modules::AgentCustomerInformationCenterSearch;
use Kernel::Modules::AgentCustomerSearch;
use Kernel::Modules::AgentDashboard;
use Kernel::Modules::AgentDashboardCommon;
use Kernel::Modules::AgentHTMLReference;
use Kernel::Modules::AgentInfo;
use Kernel::Modules::AgentLinkObject;
use Kernel::Modules::AgentPreferences;
use Kernel::Modules::AgentSchedulerInfo;
use Kernel::Modules::AgentSearch;
use Kernel::Modules::AgentSpelling;
use Kernel::Modules::AgentStats;
use Kernel::Modules::AgentTicketActionCommon;
use Kernel::Modules::AgentTicketAttachment;
use Kernel::Modules::AgentTicketBounce;
use Kernel::Modules::AgentTicketBulk;
use Kernel::Modules::AgentTicketClose;
use Kernel::Modules::AgentTicketCompose;
use Kernel::Modules::AgentTicketCustomer;
use Kernel::Modules::AgentTicketEmail;
use Kernel::Modules::AgentTicketEmailOutbound;
use Kernel::Modules::AgentTicketEscalationView;
use Kernel::Modules::AgentTicketForward;
use Kernel::Modules::AgentTicketFreeText;
use Kernel::Modules::AgentTicketHistory;
use Kernel::Modules::AgentTicketLock;
use Kernel::Modules::AgentTicketLockedView;
use Kernel::Modules::AgentTicketMerge;
use Kernel::Modules::AgentTicketMove;
use Kernel::Modules::AgentTicketNote;
use Kernel::Modules::AgentTicketOwner;
use Kernel::Modules::AgentTicketPending;
use Kernel::Modules::AgentTicketPhone;
use Kernel::Modules::AgentTicketPhoneCommon;
use Kernel::Modules::AgentTicketPhoneInbound;
use Kernel::Modules::AgentTicketPhoneOutbound;
use Kernel::Modules::AgentTicketPlain;
use Kernel::Modules::AgentTicketPrint;
use Kernel::Modules::AgentTicketPriority;
use Kernel::Modules::AgentTicketProcess;
use Kernel::Modules::AgentTicketQueue;
use Kernel::Modules::AgentTicketResponsible;
use Kernel::Modules::AgentTicketResponsibleView;
use Kernel::Modules::AgentTicketSearch;
use Kernel::Modules::AgentTicketService;
use Kernel::Modules::AgentTicketStatusView;
use Kernel::Modules::AgentTicketWatchView;
use Kernel::Modules::AgentTicketWatcher;
use Kernel::Modules::AgentTicketZoom;
use Kernel::Modules::AgentUserSearch;
use Kernel::Modules::AgentZoom;

# web admin middle ware modules
use Kernel::Modules::Admin;
use Kernel::Modules::AdminACL;
use Kernel::Modules::AdminAttachment;
use Kernel::Modules::AdminAutoResponse;
use Kernel::Modules::AdminCustomerCompany;
use Kernel::Modules::AdminCustomerUser;
use Kernel::Modules::AdminCustomerUserGroup;
use Kernel::Modules::AdminCustomerUserService;
use Kernel::Modules::AdminDynamicField;
use Kernel::Modules::AdminDynamicFieldCheckbox;
use Kernel::Modules::AdminDynamicFieldDateTime;
use Kernel::Modules::AdminDynamicFieldDropdown;
use Kernel::Modules::AdminDynamicFieldMultiselect;
use Kernel::Modules::AdminDynamicFieldText;
use Kernel::Modules::AdminEmail;
use Kernel::Modules::AdminGenericAgent;
use Kernel::Modules::AdminGenericInterfaceDebugger;
use Kernel::Modules::AdminGenericInterfaceInvokerDefault;
use Kernel::Modules::AdminGenericInterfaceMappingSimple;
use Kernel::Modules::AdminGenericInterfaceOperationDefault;
use Kernel::Modules::AdminGenericInterfaceTransportHTTPREST;
use Kernel::Modules::AdminGenericInterfaceTransportHTTPSOAP;
use Kernel::Modules::AdminGenericInterfaceWebservice;
use Kernel::Modules::AdminGenericInterfaceWebserviceHistory;
use Kernel::Modules::AdminGroup;
use Kernel::Modules::AdminInit;
use Kernel::Modules::AdminLog;
use Kernel::Modules::AdminMailAccount;
use Kernel::Modules::AdminNotification;
use Kernel::Modules::AdminNotificationEvent;
use Kernel::Modules::AdminOTRSBusiness;
use Kernel::Modules::AdminPGP;
use Kernel::Modules::AdminPackageManager;
use Kernel::Modules::AdminPerformanceLog;
use Kernel::Modules::AdminPostMasterFilter;
use Kernel::Modules::AdminPriority;
use Kernel::Modules::AdminProcessManagement;
use Kernel::Modules::AdminProcessManagementActivity;
use Kernel::Modules::AdminProcessManagementActivityDialog;
use Kernel::Modules::AdminProcessManagementPath;
use Kernel::Modules::AdminProcessManagementTransition;
use Kernel::Modules::AdminProcessManagementTransitionAction;
use Kernel::Modules::AdminQueue;
use Kernel::Modules::AdminQueueAutoResponse;
use Kernel::Modules::AdminQueueTemplates;
use Kernel::Modules::AdminRegistration;
use Kernel::Modules::AdminRole;
use Kernel::Modules::AdminRoleGroup;
use Kernel::Modules::AdminRoleUser;
use Kernel::Modules::AdminSLA;
use Kernel::Modules::AdminSMIME;
use Kernel::Modules::AdminSalutation;
use Kernel::Modules::AdminSelectBox;
use Kernel::Modules::AdminService;
use Kernel::Modules::AdminServiceCenter;
use Kernel::Modules::AdminSession;
use Kernel::Modules::AdminSignature;
use Kernel::Modules::AdminState;
use Kernel::Modules::AdminSysConfig;
use Kernel::Modules::AdminSystemAddress;
use Kernel::Modules::AdminSystemMaintenance;
use Kernel::Modules::AdminTemplate;
use Kernel::Modules::AdminTemplateAttachment;
use Kernel::Modules::AdminType;
use Kernel::Modules::AdminUser;
use Kernel::Modules::AdminUserGroup;

# web customer middle ware modules
use Kernel::Modules::CustomerAccept;
use Kernel::Modules::CustomerPreferences;
use Kernel::Modules::CustomerTicketAttachment;
use Kernel::Modules::CustomerTicketMessage;
use Kernel::Modules::CustomerTicketOverview;
use Kernel::Modules::CustomerTicketPrint;
use Kernel::Modules::CustomerTicketProcess;
use Kernel::Modules::CustomerTicketSearch;
use Kernel::Modules::CustomerTicketZoom;

# frontend modules
use Kernel::Output::HTML::ArticleAttachmentDownload;
use Kernel::Output::HTML::ArticleAttachmentHTMLViewer;
use Kernel::Output::HTML::ArticleCheckPGP;
use Kernel::Output::HTML::ArticleCheckSMIME;
use Kernel::Output::HTML::ArticleComposeCrypt;
use Kernel::Output::HTML::ArticleComposeSign;
use Kernel::Output::HTML::CustomerHeaderMetaTicketSearch;
use Kernel::Output::HTML::CustomerNewTicketQueueSelectionGeneric;
use Kernel::Output::HTML::CustomerUserGeneric;
use Kernel::Output::HTML::CustomerUserGenericTicket;
use Kernel::Output::HTML::DashboardCalendar;
use Kernel::Output::HTML::DashboardCmdOutput;
use Kernel::Output::HTML::DashboardCustomerCompanyInformation;
use Kernel::Output::HTML::DashboardCustomerIDStatus;
use Kernel::Output::HTML::DashboardCustomerUserList;
use Kernel::Output::HTML::DashboardEventsTicketCalendar;
use Kernel::Output::HTML::DashboardIFrame;
use Kernel::Output::HTML::DashboardImage;
use Kernel::Output::HTML::DashboardMOTD;
use Kernel::Output::HTML::DashboardNews;
use Kernel::Output::HTML::DashboardProductNotify;
use Kernel::Output::HTML::DashboardRSS;
use Kernel::Output::HTML::DashboardStats;
use Kernel::Output::HTML::DashboardTicketGeneric;
use Kernel::Output::HTML::DashboardTicketQueueOverview;
use Kernel::Output::HTML::DashboardTicketStatsGeneric;
use Kernel::Output::HTML::DashboardUserOnline;
use Kernel::Output::HTML::DashboardUserOutOfOffice;
use Kernel::Output::HTML::HeaderMetaRefresh;
use Kernel::Output::HTML::HeaderMetaTicketSearch;
use Kernel::Output::HTML::Layout;
use Kernel::Output::HTML::LayoutAJAX;
use Kernel::Output::HTML::LayoutDatepicker;
use Kernel::Output::HTML::LayoutLinkObject;
use Kernel::Output::HTML::LayoutLoader;
use Kernel::Output::HTML::LayoutPopup;
use Kernel::Output::HTML::LayoutTemplate;
use Kernel::Output::HTML::LayoutTicket;
use Kernel::Output::HTML::LinkObjectTicket;
use Kernel::Output::HTML::NavBarAgentTicketProcess;
use Kernel::Output::HTML::NavBarAgentTicketService;
use Kernel::Output::HTML::NavBarCustomerCompany;
use Kernel::Output::HTML::NavBarCustomerTicketProcess;
use Kernel::Output::HTML::NavBarModuleAdmin;
use Kernel::Output::HTML::NotificationAgentOTRSBusiness;
use Kernel::Output::HTML::NotificationAgentOnline;
use Kernel::Output::HTML::NotificationAgentTicketEscalation;
use Kernel::Output::HTML::NotificationCustomerOTRSBusiness;
use Kernel::Output::HTML::NotificationCustomerOnline;
use Kernel::Output::HTML::NotificationCustomerSystemMaintenanceCheck;
use Kernel::Output::HTML::NotificationGeneric;
use Kernel::Output::HTML::NotificationOutofOfficeCheck;
use Kernel::Output::HTML::NotificationSchedulerCheck;
use Kernel::Output::HTML::NotificationSystemMaintenanceCheck;
use Kernel::Output::HTML::NotificationUIDCheck;
use Kernel::Output::HTML::OutputFilterTextAutoLink;
use Kernel::Output::HTML::OutputFilterTextURL;
use Kernel::Output::HTML::PreferencesColumnFilters;
use Kernel::Output::HTML::PreferencesCustomQueue;
use Kernel::Output::HTML::PreferencesCustomService;
use Kernel::Output::HTML::PreferencesGeneric;
use Kernel::Output::HTML::PreferencesLanguage;
use Kernel::Output::HTML::PreferencesOutOfOffice;
use Kernel::Output::HTML::PreferencesPGP;
use Kernel::Output::HTML::PreferencesPassword;
use Kernel::Output::HTML::PreferencesSMIME;
use Kernel::Output::HTML::PreferencesSkin;
use Kernel::Output::HTML::PreferencesTheme;
use Kernel::Output::HTML::PreferencesTicketWatcher;
use Kernel::Output::HTML::PreferencesTimeZone;
use Kernel::Output::HTML::QueuePreferencesGeneric;
use Kernel::Output::HTML::SLAPreferencesGeneric;
use Kernel::Output::HTML::ServicePreferencesGeneric;
use Kernel::Output::HTML::TicketMenuGeneric;
use Kernel::Output::HTML::TicketMenuLock;
use Kernel::Output::HTML::TicketMenuMove;
use Kernel::Output::HTML::TicketMenuProcess;
use Kernel::Output::HTML::TicketMenuResponsible;
use Kernel::Output::HTML::TicketMenuTicketWatcher;
use Kernel::Output::HTML::TicketOverviewMedium;
use Kernel::Output::HTML::TicketOverviewMenuSort;
use Kernel::Output::HTML::TicketOverviewPreview;
use Kernel::Output::HTML::TicketOverviewSmall;
use Kernel::Output::HTML::ToolBarGeneric;
use Kernel::Output::HTML::ToolBarLink;
use Kernel::Output::HTML::ToolBarTicketLocked;
use Kernel::Output::HTML::ToolBarTicketResponsible;
use Kernel::Output::HTML::ToolBarTicketSearchFulltext;
use Kernel::Output::HTML::ToolBarTicketSearchProfile;
use Kernel::Output::HTML::ToolBarTicketService;
use Kernel::Output::HTML::ToolBarTicketWatcher;
use Kernel::Output::Template::Document;
use Kernel::Output::Template::Plugin::OTRS;
use Kernel::Output::Template::Provider;

1;
